language: python

install:
  - "pip install coveralls flake8 mopidy"

script:
  - "flake8 $(find . -iname '*.py')"
  - "nosetests --with-coverage --cover-package=mopidy_scrobbler"

after_success:
  - "coveralls"

notifications:
  irc:
    channels:
      - "irc.freenode.org#mopidy"
    on_success: change
    on_failure: change
    use_notice: true
    skip_join: true
